title: Nithin Raveendran
description: Nithin's personal website
theme: jekyll-theme-cayman
github:
  University of Arizona: https://ece.engineering.arizona.edu/faculty-staff/faculty/nithin-raveendran
  Google Scholar: https://scholar.google.com/citations?user=FBrIdeAAAAAJ
